CREATE TABLE "SENT_MSG_CONTAINER" (
    "ID" VARCHAR2(255 CHAR) PRIMARY KEY,
    "TRANSACTION_ID" VARCHAR2(255 CHAR),
    "CREATION_TIME" TIMESTAMP NOT NULL,
    "JSON_SERIALIZED_MSG" CLOB NOT NULL,
    "MSG_TYPE" VARCHAR2(255 CHAR) NOT NULL,
    "STATUS" VARCHAR2(64 CHAR),
    "TOPIC" VARCHAR2(255 CHAR) NOT NULL,
    "ORIGIN_MESSAGE" VARCHAR2(255 CHAR) NOT NULL
);

CREATE TABLE "RECEIVED_MSG_CONTAINER" (
    "ID" VARCHAR2(255 CHAR) PRIMARY KEY,
    "JSON_SERIALIZED_MSG" CLOB NOT NULL,
    "MSG_CREATION_TIME" TIMESTAMP NOT NULL,
    "MSG_TYPE" VARCHAR2(255 CHAR) NOT NULL,
    "RECEIVED_TIME" TIMESTAMP(6) NOT NULL,
    "STATUS" VARCHAR2(64 CHAR),
    "TOPIC" VARCHAR2(255 CHAR) NOT NULL,
    "ORIGIN_MESSAGE" VARCHAR2(255 CHAR) NOT NULL
);
